<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2025 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech
     Red Hat Inc

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.eclipse.kura</groupId>
    <artifactId>kura-camel</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <org.apache.camel.version>4.20.0</org.apache.camel.version>

        <org.eclipse.kura.camel.version>2.0.0-SNAPSHOT</org.eclipse.kura.camel.version>
        <org.eclipse.kura.camel.cloud.factory.version>2.0.0-SNAPSHOT</org.eclipse.kura.camel.cloud.factory.version>
        <org.eclipse.kura.camel.xml.version>2.0.0-SNAPSHOT</org.eclipse.kura.camel.xml.version>
        <org.eclipse.kura.wire.camel.version>2.0.0-SNAPSHOT</org.eclipse.kura.wire.camel.version>
    </properties>

    <modules>
        <module>target-definition</module>
        <module>bundles</module>
        <module>distrib</module>
    </modules>

    <pluginRepositories>
        <pluginRepository>
            <id>cbi</id>
            <url>https://repo.eclipse.org/content/repositories/cbi-releases/</url>
        </pluginRepository>
    </pluginRepositories>

    <distributionManagement>
        <repository>
            <id>repo.eclipse.org</id>
            <name>Kura Repository - Releases</name>
            <url>https://repo.eclipse.org/content/repositories/kura-releases/</url>
        </repository>
        <snapshotRepository>
            <id>repo.eclipse.org</id>
            <name>Kura Repository - Snapshots</name>
            <url>https://repo.eclipse.org/content/repositories/kura-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <repositories>
        <repository>
            <id>kura-releases</id>
            <name>Eclipse Kura Repository - Releases</name>
            <url>https://repo.eclipse.org/content/repositories/kura-releases/</url>
        </repository>
        <repository>
            <id>kura-snapshots</id>
            <name>Eclipse Kura Repository - Snapshots</name>
            <url>https://repo.eclipse.org/content/repositories/kura-snapshots/</url>
        </repository>
        <repository>
            <id>kura-addons</id>
            <name>Kura Addons Maven Repository</name>
            <url>https://raw.githubusercontent.com/eurotech/kura_addons/mvn-repo</url>
        </repository>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
    </repositories>

</project>
