<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  	Copyright (c) 2011, 2024 Eurotech and/or its affiliates and others
  
    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/
 
	SPDX-License-Identifier: EPL-2.0
	
	Contributors:
	 Eurotech
	 Red Hat Inc
	 
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.eclipse.kura</groupId>
		<artifactId>kura-camel.parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>org.eclipse.kura.camel</artifactId>
	<version>${org.eclipse.kura.camel.version}</version>
	<packaging>eclipse-plugin</packaging>
	<build>
		<plugins>
			 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <configuration>
                            <outputDirectory>${project.basedir}/lib</outputDirectory>
                            <stripVersion>true</stripVersion>
                            <artifactItems>
                                <artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-amqp</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-core</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
								    <groupId>org.apache.camel</groupId>
								    <artifactId>camel-core-languages</artifactId>
								    <version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-vertx</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-vertx-common</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-vertx-http</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-vertx-websocket</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-ref</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-xml-io-util</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-xml-io</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-xml-io-dsl</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-yaml-io</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-yaml-dsl</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-java-joor-dsl</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-joor</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.jooq</groupId>
									<artifactId>joor</artifactId>
									<version>0.9.15</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-base-engine</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-core-engine</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-api</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-util</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-base</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-management-api</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-support</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-core-reifier</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-core-model</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-core-processor</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-groovy</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-spring</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-spring-xml</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-netty</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-netty-http</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-util-json</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-tooling-model</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-rest</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-xml-jaxp</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-xml-jaxb</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-stream</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-http</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.httpcomponents.client5</groupId>
									<artifactId>httpclient5</artifactId>
									<version>5.5.2</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.httpcomponents.core5</groupId>
									<artifactId>httpcore5</artifactId>
									<version>5.4.2</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.httpcomponents.core5</groupId>
									<artifactId>httpcore5-h2</artifactId>
									<version>5.4.2</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-cluster</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-file</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-bean</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-timer</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-attachments</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-http-base</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-http-common</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-jms</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-paho</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-paho-mqtt5</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-core-xml</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-dsl-support</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-endpointdsl</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-endpointdsl-support</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-jackson3</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-seda</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-direct</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-servlet</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-gson</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.camel</groupId>
									<artifactId>camel-log</artifactId>
									<version>${org.apache.camel.version}</version>
								</artifactItem>
                            </artifactItems>
                        </configuration>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
		</plugins>
	</build>
</project>
